################################################################################
### Data description
# PDX data (host: mouse, graft: human)
# paired-end sequencing data
# read length : could be different depending on the study
# strand-specific : unstranded
# watch out the parameters of cutadapt/star/rsem/featureCounts based on the above information
# host and ambigious reads are excluded by 'ngs-disambiguate'

# Novel junction identification based on star 2-pass alignment
# Procedure for novel junction identification
################################################################################


options:
    bam2fastq: False
    paired: True
    novel_junction: True
    star_fusion: False
    rsem: False
    dexseq: False

samples: '/DATA/projects/j.bhin/Daniel_FGFR2/FM_pdx/pipeline/samples.test.csv'

################################################################################
# Path configuration                                                           
################################################################################

path:
    default: '/DATA/projects/j.bhin/Daniel_FGFR2/FM_pdx/AZ_TNBC'

################################################################################
# Rules
################################################################################

sort_bam:
    threads: 12

bam2fastq:
    threads: 2
    options: ''

cutadapt:
    options:
        - -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA # ILLUMINA TrueSeq R1
        - -A AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT # ILLUMINA TrueSeq R2 for paired-seq
        - --minimum-length 30
        - -q 20

# using CTAT library from Broad institute
star_align:
    # STAR index for host and graft
    index_host: '/DATA/projects/j.bhin/reference/Mouse_gencode_M23_CTAT_lib_Dec062019.plug-n-play/ctat_genome_lib_build_dir/ref_genome.fa.star.idx' 
    index_graft: '/DATA/projects/j.bhin/reference/GRCh38_gencode_v32_CTAT_lib_Dec062019.plug-n-play/ctat_genome_lib_build_dir/ref_genome.fa.star.idx' 
    threads: 12
    options:
        - --chimSegmentMin 10
        - --chimJunctionOverhangMin 10
        - --alignSJDBoverhangMin 10
        - --alignMatesGapMax 100000
        - --alignIntronMax 100000
        - --alignSJstitchMismatchNmax 5 -1 5 5
        - --outSAMattrRGline ID:GRPundef
        - --chimMultimapScoreRange 3
        - --chimScoreJunctionNonGTAG -4
        - --chimMultimapNmax 0
        - --chimNonchimScoreDropMin 10
#    - --quantMode TranscriptomeSAM  # for RSEM

    # requirements for STAR 2-pass alignment
    gtf: '/DATA/projects/j.bhin/reference/GRCh38_gencode_v32_CTAT_lib_Dec062019.plug-n-play/ctat_genome_lib_build_dir/ref_annot.gtf'
    fasta: '/DATA/projects/j.bhin/reference/GRCh38_gencode_v32_CTAT_lib_Dec062019.plug-n-play/ctat_genome_lib_build_dir/ref_genome.fa'
    threads_indexing: 24

sambamba_sort:
    threads: 4

sambamba_index:
    threads: 4

disambiguate:
    algorithm: 'STAR'
    options: ''

star_fusion:
    reflib: '/DATA/projects/j.bhin/reference/GRCh38_gencode_v32_CTAT_lib_Dec062019.plug-n-play/ctat_genome_lib_build_dir'
    threads: 12
    options:
        - --examine_coding_effect
          #        - --FusionInspector validate
          #        - --denovo_reconstruct


#rsem_reference: 
#  fa: /home/j.bhin/Resources/mouse_GRCm38/STAR_index/Mus_musculus.GRCm38.dna.primary_assembly.fa
#  gtf: /home/j.bhin/Resources/mouse_GRCm38/STAR_index/Mus_musculus.GRCm38.76.gtf
#  prefix: /home/j.bhin/Resources/mouse_GRCm38/rsem_reference/GRCm38
#  threads: 12
#  options:


#rsem_quant:
#  ref: /home/j.bhin/Resources/mouse_GRCm38/rsem_reference/GRCm38
#  threads: 12
#  options:
#    - --paired-end
#    - --forward-prob 0 # strand-specific (reverse: 0, forward: 1)
#    - --no-bam-output


featureCounts:
  gtf: '/DATA/projects/j.bhin/reference/GRCh38_v27_CTAT_lib_Feb092018/ctat_genome_lib_build_dir/ref_annot.gtf'
  threads: 8
  options:
    - -p # pair-end
    - -s 0 # 0: unstranded, 1: stranded, 2: reversely stranded
    - -O # consider the reads or read-pairs that overlaps with multiple exons or genes


#DEXseq:
#  gtf: /home/j.bhin/Resources/mouse_GRCm38/STAR_index/Mus_musculus.GRCm38.76.gtf
#  prefix: /home/j.bhin/Resources/mouse_GRCm38/DEXSeq/GRCm38_dexseq
#  options:
#    - -p yes # paired-end data
#    - -r pos # sorted by alignment position
#    - -s reverse # "yes": forward, "reverse": reverse, "no": unstranded
#    - -f bam # input is bam format
#

